[package]
name = "magic-cube"
description = "A work-in-progress rust library providing a magic cube / rubik's cube implementation."
version = "0.1.2"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/magic-cube"
repository = "https://github.com/Zitronenjoghurt/magic-cube"